### ISSUE TITLE
Cannot build project on Windows or Linux

### ISSUE THREAD

**Issue by Abdulhanan2021** [breadwallet/brd-mobile#7]
as mentioned in setup "Open the Cosmos folder using Intellij IDEA or Android Studio" there are others cosmos folder but not a folder name "cosmos" 
can someone please guide how to make a build for android.

when building whole project folder "brd-mobile"
**face this error while building project** 
Caused by: java.lang.AssertionError: Unsupported OS: windows. Expression: false
	at build_94wvs0xuo1nr69mmu6v8vw4ez.jnaOsFromGradle(C:\projects\BreadW-git\brd-mobile\external\walletkit\WalletKitJava\corenative-jre\build.gradle:23)
	at build_94wvs0xuo1nr69mmu6v8vw4ez$jnaOsFromGradle.callStatic(Unknown Source)
	at build_94wvs0xuo1nr69mmu6v8vw4ez.jnaResourceFromGradle(C:\projects\BreadW-git\brd-mobile\external\walletkit\WalletKitJava\corenative-jre\build.gradle:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at build_94wvs0xuo1nr69mmu6v8vw4ez$_run_closure1$_closure6$_closure14$_closure29$_closure33.doCall(C:\projects\BreadW-git\brd-mobile\external\walletkit\WalletKitJava\corenative-jre\build.gradle:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.model.internal.core.NoInputsModelAction.execute(NoInputsModelAction.java:39)
	at org.gradle.model.internal.core.AbstractModelActionWithView.execute(AbstractModelActionWithView.java:37)
	at org.gradle.model.internal.registry.DefaultModelRegistry$4.run(DefaultModelRegistry.java:497)
	at org.gradle.model.internal.registry.RuleContext.run(RuleContext.java:42)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireAction(DefaultModelRegistry.java:494)
	... 148 more

**Comment by DrewCarlson** [comment]
Thanks, that documentation needs to be updated.  The root `brd-mobile` folder should be opened in Intellij IDEA or Android Studio.

The error you see is from the local [WalletKit](https://github.com/blockset-corp/walletkit) which can only be compiled on macOS.  At this time we do not have easy instructions to get setup on windows, but if you're interested you can follow the steps below.

To use the project on Windows, WalletKit must be published to your own maven repository (or locally with `./gradlew publishToMavenLocal`) and update the coordinates in [`buildSrc/src/main/kotlin/brd/Libs.kt`](https://github.com/breadwallet/brd-mobile/blob/7293d4fa2df2114c2eb265e239db68660653ade6/buildSrc/src/main/kotlin/brd/Libs.kt#L74-L76).  After you'll need to remove the composite build configuration from [`settings.gradle.kts`](https://github.com/breadwallet/brd-mobile/blob/7293d4fa2df2114c2eb265e239db68660653ade6/settings.gradle.kts#L18-L23).
